CREATE TABLE continentes (
    id_continente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(50) NOT NULL UNIQUE
);


CREATE TABLE paises (
    id_pais NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL UNIQUE,
    id_continente NUMBER NOT NULL,
    CONSTRAINT fk_paises_continentes
        FOREIGN KEY (id_continente)
        REFERENCES continentes (id_continente)
);


CREATE TABLE vacinas_obrigatorias_viagem (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pais NUMBER NOT NULL,
    nome_vacina VARCHAR2(150) NOT NULL,
    grupo_de_risco VARCHAR2(200),
    CONSTRAINT fk_vacinas_paises
        FOREIGN KEY (id_pais)
        REFERENCES paises (id_pais)
        ON DELETE CASCADE
)
