CREATE TABLE CONTINENTES (
    ID_CONTINENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE PAISES (
    ID_PAIS INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL UNIQUE,
    ID_CONTINENTE INT NOT NULL,
    CONSTRAINT FK_PAISES_CONTINENTES
        FOREIGN KEY (ID_CONTINENTE)
        REFERENCES CONTINENTES (ID_CONTINENTE)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE VACINAS_OBRIGATORIAS_VIAGEM (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_PAIS INT NOT NULL,
    NOME_VACINA VARCHAR(150) NOT NULL,
    GRUPO_DE_RISCO VARCHAR(200),
    CONSTRAINT FK_VACINAS_PAISES
        FOREIGN KEY (ID_PAIS)
        REFERENCES PAISES (ID_PAIS)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
