PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS CONTINENTES (
    ID_CONTINENTE INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS PAISES (
    ID_PAIS INTEGER PRIMARY KEY AUTOINCREMENT,
    NOME TEXT NOT NULL UNIQUE,
    ID_CONTINENTE INTEGER NOT NULL,
    FOREIGN KEY (ID_CONTINENTE)
        REFERENCES CONTINENTES (ID_CONTINENTE)
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS VACINAS_OBRIGATORIAS_VIAGEM (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_PAIS INTEGER NOT NULL,
    NOME_VACINA TEXT NOT NULL,
    GRUPO_DE_RISCO TEXT,
    FOREIGN KEY (ID_PAIS)
        REFERENCES PAISES (ID_PAIS)
        ON DELETE CASCADE
);
