INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO)
VALUES ((SELECT ID_PAIS FROM PAISES WHERE NOME='Gana'),
        'Febre Amarela', 'Todos os viajantes');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO)
VALUES ((SELECT ID_PAIS FROM PAISES WHERE NOME='Angola'),
        'Febre Amarela', 'Todos os viajantes');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Nigéria'),
 'Febre Amarela', 'Todos os viajantes');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Guiné'),
 'Febre Amarela', 'Todos os viajantes');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Guiné-Bissau'),
 'Febre Amarela', 'Todos os viajantes');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Guiné Equatorial'),
 'Febre Amarela', 'Todos os viajantes');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='República Democrática do Congo'),
 'Febre Amarela', 'Todos os viajantes');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Sudão do Sul'),
 'Febre Amarela', 'Todos os viajantes');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Guiana Francesa'),
 'Febre Amarela', 'Todos os viajantes');

-- RISCO MODERADO
INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='África do Sul'),
 'Febre Amarela', 'Viajantes vindos de países com risco');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Namíbia'),
 'Febre Amarela', 'Viajantes vindos de países com risco');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Botswana'),
 'Febre Amarela', 'Viajantes vindos de países com risco');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Zâmbia'),
 'Febre Amarela', 'Viajantes vindos de países com risco');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Zimbábue'),
 'Febre Amarela', 'Viajantes vindos de países com risco');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Quênia'),
 'Febre Amarela', 'Viajantes vindos de países com risco');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Tanzânia'),
 'Febre Amarela', 'Viajantes vindos de países com risco');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Ruanda'),
 'Febre Amarela', 'Viajantes vindos de países com risco');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Uganda'),
 'Febre Amarela', 'Viajantes vindos de países com risco');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Egito'),
 'Febre Amarela', 'Viajantes vindos de países com risco');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Índia'),
 'Febre Amarela', 'Viajantes vindos de países com risco');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Indonésia'),
 'Febre Amarela', 'Viajantes vindos de países com risco');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Malásia'),
 'Febre Amarela', 'Viajantes vindos de países com risco');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Singapura'),
 'Febre Amarela', 'Viajantes vindos de países com risco');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Tailândia'),
 'Febre Amarela', 'Viajantes vindos de países com risco');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Panamá'),
 'Febre Amarela', 'Viajantes vindos de países com risco');

-- MENINGITE
INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Arábia Saudita'),
 'Meningite ACWY', 'Peregrinos do Hajj e Umrah');

-- POLIOMIELITE
INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Afeganistão'),
 'Poliomielite (IPV)', 'Viajantes de longa permanência');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Paquistão'),
 'Poliomielite (IPV)', 'Viajantes de longa permanência');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Somália'),
 'Poliomielite (IPV)', 'Viajantes de longa permanência');

-- COVID-19
INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='China'),
 'COVID-19', 'Restrições específicas');

INSERT INTO VACINAS_OBRIGATORIAS_VIAGEM (ID_PAIS, NOME_VACINA, GRUPO_DE_RISCO) VALUES
((SELECT ID_PAIS FROM PAISES WHERE NOME='Indonésia'),
 'COVID-19', 'Restrições específicas');
