INSERT INTO CONTINENTES (NOME) VALUES ('África');
INSERT INTO CONTINENTES (NOME) VALUES ('América do Norte');
INSERT INTO CONTINENTES (NOME) VALUES ('América do Sul');
INSERT INTO CONTINENTES (NOME) VALUES ('Ásia');
INSERT INTO CONTINENTES (NOME) VALUES ('Europa');
INSERT INTO CONTINENTES (NOME) VALUES ('Oceania');
INSERT INTO CONTINENTES (NOME) VALUES ('Antártida');